name: Deploy to Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'functions/mainSummaryTranslation'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package Lambda function
      run: |
        zip -r lambda_function.zip * -x "*.git*"

    - name: Configure AWS credentials from IAM Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::618044871166:role/githubActions
        aws-region: us-east-1

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name transcribeSummary-mainSummaryTranslation --zip-file fileb://lambda_function.zip